name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - uses: purescript-contrib/setup-purescript@main

      - run: yarn
      - run: spago test
      - run: yarn build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
